version: "3.8"

services:
  django_app:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:password@db:5432/django_db
    depends_on:
      - db

  go_service:
    build:
      context: ./go_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  grpc_service:
    build:
      context: ./grpc_service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

