# Generated by Django 4.2.17 on 2024-12-20 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('reservation_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=10)),
                ('catering_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hauberge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hostels.hauberge')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
